# Generated by Django 4.2.8 on 2023-12-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busca_especialista", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
