# Generated by Django 4.2.8 on 2023-12-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busca_especialista", "0002_professional_email_alter_cities_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professional",
            name="email",
            field=models.EmailField(
                blank=True, max_length=30, null=True, verbose_name="E-mail"
            ),
        ),
    ]
