# Generated by Django 4.2.8 on 2023-12-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busca_especialista", "0003_alter_professional_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professional",
            name="email",
            field=models.EmailField(
                blank=True, max_length=50, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="instagram_user",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Instagram"
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="whatsapp_number",
            field=models.CharField(max_length=15, verbose_name="Whatsapp"),
        ),
        migrations.AlterField(
            model_name="services",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="services",
            name="service",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
